### ISSUE TITLE
tests are failing sometimes due to container failures 

### ISSUE THREAD

**Issue by anpin** [akkadotnet/Akka.Persistence.Linq2Db#362]
**Version Information**
latest dev branch

**Describe the bug**
Sometimes running test locally and in CI fails due to container startup timeout 

**To Reproduce**
Run tests a few times 

**Expected behavior**
Test runs are consistent and containers are starting smoothly 

**Actual behavior**

[log](https://dev.azure.com/dotnet/fa49bc58-13a9-42fb-8dd1-307759222d95/_apis/build/builds/105053/logs/20)
```
2024-04-17T22:57:07.3196154Z   Passed Sql should be able to query events by persistence id on data created by other persistence plugin [405 ms]
2024-04-17T22:58:08.0647740Z [xUnit.net 00:18:57.53]     Sql should recover data created using other persistence plugins [FAIL]
2024-04-17T22:58:08.8334824Z [xUnit.net 00:18:57.54]       System.Exception : Docker image failed to run within 00:01:00.
2024-04-17T22:58:08.8335818Z [xUnit.net 00:18:57.54]       Stack Trace:
2024-04-17T22:58:08.8336357Z [xUnit.net 00:18:57.54]         /home/vsts/work/1/s/src/Akka.Persistence.Sql.Data.Compatibility.Tests/Internal/DockerContainer.cs(174,0): at Akka.Persistence.Sql.Data.Compatibility.Tests.Internal.DockerContainer.AwaitUntilReadyAsync(String marker, TimeSpan timeout)
2024-04-17T22:58:08.8337183Z [xUnit.net 00:18:57.54]         /home/vsts/work/1/s/src/Akka.Persistence.Sql.Data.Compatibility.Tests/Internal/DockerContainer.cs(120,0): at Akka.Persistence.Sql.Data.Compatibility.Tests.Internal.DockerContainer.InitializeAsync()
2024-04-17T22:58:08.8337919Z [xUnit.net 00:18:57.54]         /home/vsts/work/1/s/src/Akka.Persistence.Sql.Data.Compatibility.Tests/DataCompatibilitySpecBase.cs(59,0): at Akka.Persistence.Sql.Data.Compatibility.Tests.DataCompatibilitySpecBase`1.InitializeAsync()
2024-04-17T22:58:08.8338506Z   Failed Sql should recover data created using other persistence plugins [1 ms]
2024-04-17T22:58:08.8338832Z   Error Message:
2024-04-17T22:58:08.8339116Z    System.Exception : Docker image failed to run within 00:01:00.
2024-04-17T22:58:08.8339477Z   Stack Trace:
2024-04-17T22:58:08.8339938Z      at Akka.Persistence.Sql.Data.Compatibility.Tests.Internal.DockerContainer.AwaitUntilReadyAsync(String marker, TimeSpan timeout) in /home/vsts/work/1/s/src/Akka.Persistence.Sql.Data.Compatibility.Tests/Internal/DockerContainer.cs:line 174
2024-04-17T22:58:08.8341270Z    at Akka.Persistence.Sql.Data.Compatibility.Tests.Internal.DockerContainer.InitializeAsync() in /home/vsts/work/1/s/src/Akka.Persistence.Sql.Data.Compatibility.Tests/Internal/DockerContainer.cs:line 120
2024-04-17T22:58:08.8341955Z    at Akka.Persistence.Sql.Data.Compatibility.Tests.DataCompatibilitySpecBase`1.InitializeAsync() in /home/vsts/work/1/s/src/Akka.Persistence.Sql.Data.Compatibility.Tests/DataCompatibilitySpecBase.cs:line 59
```

**Screenshots**

**Environment**
Locally on linux and on azure devops

**Additional context**
`GetContainerLogsAsync` marked as obsolete and called right before the warm waiting loop

https://github.com/akkadotnet/Akka.Persistence.Sql/blob/fe49a6bd028763d99b07c889d787d1ffa58acb81/src/Akka.Persistence.Sql.Tests.Common/Containers/DockerContainer.cs#L115

https://github.com/akkadotnet/Akka.Persistence.Sql/blob/fe49a6bd028763d99b07c889d787d1ffa58acb81/src/Akka.Persistence.Sql.Data.Compatibility.Tests/Internal/DockerContainer.cs#L105

**Comment by anpin** [comment]
Can't run local tests against mssql container due to https://github.com/microsoft/mssql-docker/issues/868

```console
└[~/projects/Akka.Persistence.Sql]> uname -r
6.7.6
```
